export const Adjectives = [
  {
    bisaya: "dako",
    english: "big",
    example_bisaya: "Dako ang balay.",
    example_english: "The house is big.",
  },
  {
    bisaya: "bag-o",
    english: "new",
    example_bisaya: "Bag-o ang sinina.",
    example_english: "The clothes are new.",
  },
  {
    bisaya: "daot",
    english: "bad / broken",
    example_bisaya: "Daot ang pultahan.",
    example_english: "The door is broken.",
  },
  {
    bisaya: "hugaw",
    english: "dirty",
    example_bisaya: "Hugaw ang lawak.",
    example_english: "The room is dirty.",
  },
  {
    bisaya: "kusog",
    english: "strong / fast / loud",
    example_bisaya: "Kusog ang hangin.",
    example_english: "The wind is strong.",
  },
  {
    bisaya: "hinay",
    english: "slow / gentle / quiet",
    example_bisaya: "Hinay ang tubig sa gripo.",
    example_english: "The water in the tap is slow.",
  },
  {
    bisaya: "maanyag",
    english: "beautiful / pretty",
    example_bisaya: "Maanyag ang bulak.",
    example_english: "The flower is beautiful.",
  },
  {
    bisaya: "nindot",
    english: "nice / good",
    example_bisaya: "Nindot ang sinina.",
    example_english: "The clothes are nice.",
  },
  {
    bisaya: "luya",
    english: "weak / tired",
    example_bisaya: "Luya siya karon.",
    example_english: "He is tired now.",
  },
  {
    bisaya: "kusgan",
    english: "strong / muscular",
    example_bisaya: "Kusgan ang amahan.",
    example_english: "The father is strong.",
  },
  {
    bisaya: "hayag",
    english: "bright / light",
    example_bisaya: "Hayag ang lawak.",
    example_english: "The room is bright.",
  },
  {
    bisaya: "ngitngit",
    english: "dark",
    example_bisaya: "Ngitngit ang kwarto.",
    example_english: "The room is dark.",
  },
  {
    bisaya: "lapad",
    english: "wide",
    example_bisaya: "Lapad ang dalan.",
    example_english: "The road is wide.",
  },
  {
    bisaya: "gamhanan",
    english: "powerful / mighty",
    example_bisaya: "Gamhanan ang amahan.",
    example_english: "The father is powerful.",
  },
  {
    bisaya: "hilom",
    english: "quiet / silent",
    example_bisaya: "Hilom ang lawak.",
    example_english: "The room is quiet.",
  },
  {
    bisaya: "batan-on",
    english: "young",
    example_bisaya: "Batan-on pa ang bata.",
    example_english: "The child is still young.",
  },
  {
    bisaya: "tigulang",
    english: "old / elderly",
    example_bisaya: "Tigulang na siya.",
    example_english: "He is old.",
  },
  {
    bisaya: "busog",
    english: "full / satisfied",
    example_bisaya: "Busog na siya.",
    example_english: "He is full.",
  },
  {
    bisaya: "mainiton",
    english: "warm / affectionate",
    example_bisaya: "Mainiton ang iyang kasingkasing.",
    example_english: "His heart is warm.",
  },
  {
    bisaya: "hayahay",
    english: "comfortable / relaxed",
    example_bisaya: "Hayahay sa balay karon.",
    example_english: "It’s comfortable at home now.",
  },
];
