export const Other = [
  {
    bisaya: "ako",
    english: "I / me",
    example_bisaya: "Ako ang maglimpyo karon.",
    example_english: "I will clean now.",
  },
  {
    bisaya: "ikaw",
    english: "you",
    example_bisaya: "Ikaw ang mu-abli sa pultahan.",
    example_english: "You will open the door.",
  },
  {
    bisaya: "siya",
    english: "he / she",
    example_bisaya: "Siya ang nag-ayo sa salog.",
    example_english: "He/She fixed the floor.",
  },
  {
    bisaya: "kini",
    english: "this",
    example_bisaya: "Kini ang imong sinina.",
    example_english: "This is your clothes.",
  },
  {
    bisaya: "kana",
    english: "that",
    example_bisaya: "Kana ang akong libro.",
    example_english: "That is my book.",
  },
  {
    bisaya: "unsa",
    english: "what",
    example_bisaya: "Unsa imong gibuhat?",
    example_english: "What did you do?",
  },
  {
    bisaya: "asa",
    english: "where",
    example_bisaya: "Asa ang pultahan?",
    example_english: "Where is the door?",
  },
  {
    bisaya: "kanus-a",
    english: "when",
    example_bisaya: "Kanus-a ka mouli?",
    example_english: "When will you come home?",
  },
  {
    bisaya: "ngano",
    english: "why",
    example_bisaya: "Ngano wala ka maglimpyo?",
    example_english: "Why didn’t you clean?",
  },
  {
    bisaya: "unsaon",
    english: "how",
    example_bisaya: "Unsaon nako pag-abli niini?",
    example_english: "How do I open this?",
  },
  {
    bisaya: "ug",
    english: "and",
    example_bisaya: "Kuhaa ang libro ug sinina.",
    example_english: "Get the book and the clothes.",
  },
  {
    bisaya: "o",
    english: "or",
    example_bisaya: "Palunga ang suga o ang TV?",
    example_english: "Turn off the light or the TV?",
  },
  {
    bisaya: "pero",
    english: "but",
    example_bisaya: "Gusto ko magdula, pero busy ko.",
    example_english: "I want to play, but I’m busy.",
  },
  {
    bisaya: "dili",
    english: "not / no",
    example_bisaya: "Dili ko mokaon karon.",
    example_english: "I won’t eat now.",
  },
  {
    bisaya: "na",
    english: "already / now",
    example_bisaya: "Human na ang trabaho.",
    example_english: "The work is done already.",
  },
  {
    bisaya: "pa",
    english: "still / yet",
    example_bisaya: "Nagtuon pa siya.",
    example_english: "He is still studying.",
  },
  {
    bisaya: "gyud",
    english: "really / indeed",
    example_bisaya: "Nindot gyud ang sinina.",
    example_english: "The clothes are really nice.",
  },
  {
    bisaya: "ra",
    english: "only / just",
    example_bisaya: "Ako ra ang maglimpyo.",
    example_english: "I’m the only one cleaning.",
  },
  {
    bisaya: "naay",
    english: "there is / have",
    example_bisaya: "Naay libro sa lamesa.",
    example_english: "There is a book on the table.",
  },
  {
    bisaya: "wala",
    english: "there isn’t / don’t have / none",
    example_bisaya: "Wala nay tubig sa gripo.",
    example_english: "There is no water in the tap.",
  },

  // 30 more
  {
    bisaya: "alang",
    english: "for",
    example_bisaya: "Alang sa bata kini.",
    example_english: "This is for the child.",
  },
  {
    bisaya: "gikan",
    english: "from",
    example_bisaya: "Gikan ko sa eskwelahan.",
    example_english: "I came from school.",
  },
  {
    bisaya: "sa",
    english: "at / in / on",
    example_bisaya: "Naa ko sa balay.",
    example_english: "I’m at home.",
  },
  {
    bisaya: "paingon",
    english: "towards",
    example_bisaya: "Paingon sa lamesa ang libro.",
    example_english: "The book is towards the table.",
  },
  {
    bisaya: "uban",
    english: "with / together",
    example_bisaya: "Kauban nako siya.",
    example_english: "I’m with him/her.",
  },
  {
    bisaya: "alang sa",
    english: "for the sake of",
    example_bisaya: "Alang sa imong kaayohan.",
    example_english: "For your own good.",
  },
  {
    bisaya: "kaniadto",
    english: "before / in the past",
    example_bisaya: "Kaniadto, walay TV.",
    example_english: "Before, there was no TV.",
  },
  {
    bisaya: "karon",
    english: "now / these days",
    example_bisaya: "Karon, nagtuon siya.",
    example_english: "Now, he is studying.",
  },
  {
    bisaya: "gikan sa",
    english: "from (place / source)",
    example_bisaya: "Gikan sa merkado ang prutas.",
    example_english: "The fruit is from the market.",
  },
  {
    bisaya: "ingon",
    english: "say / like",
    example_bisaya: "Ingon siya nga moabot siya.",
    example_english: "He said he will come.",
  },
  {
    bisaya: "pa-uli",
    english: "going home",
    example_bisaya: "Pa-uli na ko.",
    example_english: "I’m going home now.",
  },
  {
    bisaya: "daghan",
    english: "many / a lot",
    example_bisaya: "Daghan ang libro.",
    example_english: "There are many books.",
  },
  {
    bisaya: "pila",
    english: "how many / how much",
    example_bisaya: "Pila ka libro ang naa nimo?",
    example_english: "How many books do you have?",
  },
  {
    bisaya: "unsa pa",
    english: "what else",
    example_bisaya: "Unsa pa imong kinahanglan?",
    example_english: "What else do you need?",
  },
  {
    bisaya: "kani",
    english: "this one",
    example_bisaya: "Kani ang akong sinina.",
    example_english: "This one is my clothes.",
  },
  {
    bisaya: "kana",
    english: "that one",
    example_bisaya: "Kana ang imong libro.",
    example_english: "That one is your book.",
  },
  {
    bisaya: "ugma",
    english: "tomorrow",
    example_bisaya: "Ugma, maglimpyo ta.",
    example_english: "Tomorrow, we’ll clean.",
  },
  {
    bisaya: "gahapon",
    english: "yesterday",
    example_bisaya: "Gahapon, nagdula siya.",
    example_english: "Yesterday, he played.",
  },
  {
    bisaya: "kini ra",
    english: "only this",
    example_bisaya: "Kini ra ang naa ko.",
    example_english: "I only have this.",
  },
  {
    bisaya: "paspas",
    english: "quickly / fast",
    example_bisaya: "Paspas og limpyo.",
    example_english: "Clean quickly.",
  },
  {
    bisaya: "hinay-hinay",
    english: "slowly / gently",
    example_bisaya: "Hinay-hinay sa pagdala.",
    example_english: "Carry it slowly.",
  },
  {
    bisaya: "alang nimo",
    english: "for you",
    example_bisaya: "Alang nimo kini.",
    example_english: "This is for you.",
  },
  {
    bisaya: "uban nimo",
    english: "with you",
    example_bisaya: "Kauban nimo ko.",
    example_english: "I’m with you.",
  },
  {
    bisaya: "bisan",
    english: "even / although",
    example_bisaya: "Bisan siya bata pa, makatabang na.",
    example_english: "Even though he is young, he can help.",
  },
  {
    bisaya: "sa diha-diha",
    english: "immediately",
    example_bisaya: "Sa diha-diha, moabot siya.",
    example_english: "He will come immediately.",
  },
  {
    bisaya: "paingon sa",
    english: "heading to / towards",
    example_bisaya: "Paingon sa balay ang bata.",
    example_english: "The child is heading to the house.",
  },
  {
    bisaya: "duol",
    english: "near",
    example_bisaya: "Duol ang lamesa sa pultahan.",
    example_english: "The table is near the door.",
  },
  {
    bisaya: "layo",
    english: "far",
    example_bisaya: "Layo ang merkado.",
    example_english: "The market is far.",
  },
  {
    bisaya: "alang ra",
    english: "just for / only for",
    example_bisaya: "Alang ra sa imong kaayohan.",
    example_english: "Just for your own good.",
  },
  {
    bisaya: "sa wala pa",
    english: "before / not yet",
    example_bisaya: "Sa wala pa ka moabot, nagdula na siya.",
    example_english: "Before you arrived, he was already playing.",
  },
  {
    bisaya: "pa-una",
    english: "first / ahead",
    example_bisaya: "Pa-una siya sa linya.",
    example_english: "Let him go first in line.",
  },
];
